### ISSUE TITLE
Count matrix filled with zeros

### ISSUE THREAD

**Issue by annajbott** [CenterForStatistics-UGent/SPsimSeq#11]
I am trying to simulate bulk RNA sequencing count matrices. I have source data with 1000s of genes, 6 samples, belonging to two different groups. I am trying to create a simulated counts matrix of 6 samples consisiting of two groups, with 453 genes. I have followed your bulk example but used my own bulk RNA dataset. 

Similar to issue: **"No DE detected, error in sample.int(length(x), size, replace, prob): invalid first argument. #3"**
I received the error:
`Note: The number of DE genes detected in the source data is 0 and the number of DE genes required to be included in the simulated data is 50. Therefore, candidiate DE genes are sampled with replacement.`

I am using variations of this code, varying all of the threshold parameters:
```
sim.data.bulk <- SPsimSeq(n.sim = 1, s.data = subset_df_mRNA2, batch = NULL,
                          group = subset_df_mRNA.status, n.genes = genes, batch.config = batch.config,
                          group.config = c(0.5,0.5), tot.samples = 6, 
                          pDE = DE, lfc.thrld = 0.5, lfc.thrld = 0.2, llStat.thrld = 3, 
                          result.format = "list",  seed = seed, model.zero.prob = FALSE )
```

So I set the DE thresholds lower and got like between 1-10 DE genes. 
However I noticed that the matrix that is outputted is mainly filled with zeros, which is extremely unhelpful. Despite my source data having very few zeros in. 
It's bizarre though because I set pDE originally to values ranging from 0.01 to 0.5, and I know a that from my source data I have **a lot** of DE genes.

I was wondering if it could be picking up the groups wrong? For my source data I have a data frame with samples 1-6 along the top, samples 1-3 being from group1 and samples 4-6 being from group 2. 
I set group by: 
`subset_df_mRNA.status = c(0,0,0,1,1,1)`

And yet it still claims there are no DE genes in my source data. Here is an example line from my source data (clearly very differentially expressed between groups 1 and 2):

```
   sample1 sample2 sample3 sample4 sample5 sample6
gene3 229     175     216       0       2       1
```

Am I doing anything wrong?? Thanks!

Best wishes,
Anna

**Comment by AlemuTA** [comment]
Hi Anna,

I guess your source data (```subset_df_mRNA2```) has only 3 samples per group, right? If so, it would be difficult for the program to fit the distributions of the gene expression levels. The method relies on log-linear models that require at least 10 samples per group to fit the distribution properly and simulate a new dataset. This is the reason why you are seeing many zeroes than in the source dataset. For such a small size source data, I would use parametric simulation methods using, for example, negative binomial simulation.

Regards,
Alemu

**Comment by annajbott** [comment]
Ah I see, that makes sense! Thanks!

BW,
Anna
