### ISSUE TITLE
Question about Simulate Data   

### ISSUE THREAD

**Issue by caiquanyou** [CenterForStatistics-UGent/SPsimSeq#16]
Hi,
I have try this package with the Demo data, it is a good work!
And I have a real problem about simulate data and I  don't know this package could work or not?
Q: I want to simulate the low-quality scRNA seq data(for example , split-seq data) by adding noise to the high quality scRNA seq data(for example, smart-seq2 data) , does it possibly work in this condition?
Best!

**Comment by AlemuTA** [comment]
Hi, I'm not sure what you mean by adding a noise. SPsimSeq can simulate new datasets starting from any expression matrix, and that matrix can be less noisy or may contain highly variable samples. If your source data is a combination of two different assays, you can still use SPsimSeq but the simulated data will not let you know which simulated sample/cell is from which assay,

Best!
Alemu
