### ISSUE TITLE
Error in (exp(Y.star) - prior.count) * LL :    non-numeric argument to binary operator

### ISSUE THREAD

**Issue by duohongrui** [CenterForStatistics-UGent/SPsimSeq#17]
Yesterday I learned SPsimSeq and followed the demonstrations without errors, finding that this tool is of vital importance for my research. Then I used it with my dataset and I met a strange problem when I used it to simulate single-cell RNA sequencing data. **Could you help me?**
The reference (input) dataset was download from GEO with the accession number GSE109774 and I got a subset of the data with 1000 genes and 1000 cells. After I ran the following codes, I met the problem like this: **Error in (exp(Y.star) - prior.count) * LL :  non-numeric argument to binary operator.** It occurred after the signal "Simulating data ...  ...1 of 2"

```
>index_cell <- sample(1:2242, 1000, replace = F)
>index_gene <- sample(1:12797, 1000, replace = F)
>Limb_Muscle <- Limb_Muscle[index_gene, index_cell]
>sc_Limb_data <- SingleCellExperiment(assays=list(counts=Limb_Muscle))
>sc_Limb_data$"group" <- factor(c(rep('ill', 400), rep('healthy', 600)), levels = c('ill', 'healthy'))

>t1 <- Sys.time()
>sim.data.sc_Limb <- SPsimSeq(n.sim = 2,
                              s.data = sc_Limb_data,
                              group = sc_Limb_data$group, 
                              n.genes = 4000,
                              batch.config = 1,
                              group.config = c(0.5, 0.5),
                              tot.samples = 200, 
                              pDE = 0.3,
                              lfc.thrld = 0.5,
                              model.zero.prob = TRUE,
                              result.format = "SCE",
                              variable.lib.size = TRUE,
                              return.details = TRUE)
>t2 <- Sys.time()
>time <- t2-t1
>time
```

Where is the problem derived from? And how to solve it? **Please help me. Thanks so much.**

**Comment by AlemuTA** [comment]
Can you try by changing variable.lib.size = TRUE to variable.lib.size = FALSE?

It looks there is a problem when it fits the distribution of library sizes.

**Comment by duohongrui** [comment]
Thanks so much. I will try again later.

**Comment by duohongrui** [comment]
That works. Thanks very much.
