### ISSUE TITLE
Error when setting SPsimSeq's parameter genewiseCor to FALSE

### ISSUE THREAD

**Issue by Felitsiya** [CenterForStatistics-UGent/SPsimSeq#19]
Setting genewiseCor = FALSE then simulating data with SPsimSeq() gives me the following:

Error in genCopula(corMats.batch, exprmt.design = exprmt.design) :
object 'corMats.batch' not found.

Thank you for troubleshooting.

**Comment by AlemuTA** [comment]
Hi Felitsiya,

This problem is fixed in the latest version of SPsimSeq available here on GitHub. Please install the new version using the following lines of code.

library(devtools)
install_github("CenterForStatistics-UGent/SPsimSeq")
