### ISSUE TITLE
Returns an error when no DE genes are detected, a problem in sample()

### ISSUE THREAD

**Issue by sthawinke** [CenterForStatistics-UGent/SPsimSeq#2]

**Comment by AlemuTA** [comment]
Hi Stijn,

Try to change (lower it) the lfc.thrld, or  llStat.thrld (or both). For example
`
SPsimSeq(... lfc.thrld = 0.25, llStat.thrld = 3, ...)

If this does't work, may be try it with
SPsimSeq(... const=1) 

Regards,
Alemu
