### ISSUE TITLE
Independent library size sampling in every MC loop

### ISSUE THREAD

**Issue by sthawinke** [CenterForStatistics-UGent/SPsimSeq#7]
Not strictly necessary but may be an improvement

**Comment by AlemuTA** [comment]
Seems reasonable. My old version was also like that but since the generated library sizes are "expected library sizes", I was thinking of keeping them the same for every MC loop. I will add it as an option.

**Comment by AlemuTA** [comment]
There is an option in the new version (v2.0.2) that allows using varying library sizes for each MC simulation. This can be achieved by using the argument ```SPsimSeq(..., variale.lib.size=TRUE, ...)```.
